name: sncf_weather
description: Coding test for SNCF

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  provider: ^6.0.3
  http: ^0.13.5
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner:
  json_serializable: '>4.7.0'
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/


  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext-Regular.ttf
        - asset: assets/fonts/AvenirNext-Medium.ttf
          weight: 600
        - asset: assets/fonts/AvenirNext-Bold.ttf
          weight: 700
        - asset: assets/fonts/AvenirNext-UltraLight.ttf
          weight: 300
        - asset: assets/fonts/AvenirNext-Italic.ttf
          style: italic

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48